### PR TITLE
Simplify brew installation

### PR DESCRIPTION
**Pull request by vinkla**
This update will both tap and install the library at once.

### CODE REVIEW

**Comment by Leandros** [comment]
Déjà vu? https://github.com/tldr-pages/tldr-cpp-client/pull/4
I'm not going to merge it here, since I want to encourage people to install the upstream version of tldr.

**Comment by vinkla** [comment]
Upstream version? How do you mean?

**Comment by Leandros** [comment]
upstream equals the current master branch.

**Comment by vinkla** [comment]
Why can't we change this then? Doesn't brew fetch master anyway?

**Comment by Leandros** [comment]
Not unless you specify `--HEAD` when installing.

**Comment by waldyrious** [comment]
As a user, I'd rather use a single command with `--HEAD` than two commands even if they are individually simpler.

**Comment by vinkla** [comment]
@Leandros so it fetches the latest release instead of HEAD?

**Comment by Leandros** [comment]
```
brew install tldr-pages/tldr/tldr --HEAD
Error: No head is defined for tldr-pages/tldr/tldr
```

**Comment by vinkla** [comment]
Aah, to bad :disappointed:

**Comment by Leandros** [comment]
https://github.com/tldr-pages/homebrew-tldr/commit/b4a701e5c7225a268c7c4dbb70bb534af4950720

**Comment by vinkla** [comment]
:+1:

**Comment by vinkla** [comment]
Still think the `HEAD` isn't necessary though.

**Comment by Leandros** [comment]
> stable

and 

> release often

don't play nice together.

**Pull request closed without merging**
